spring:
  application:
    # 유레카에 등록될 이름
    name: gateway-service
  cloud:
    gateway:
      # 라우팅 설정
      routes:
        - id: test-service
          # lb:// 는 유레카에 등록된 서비스 이름으로 로드밸런싱
          uri: lb://test-service
          predicates:
            # /test-service-a/** 경로로 들어오는 요청을 test-service 로 라우팅
            - Path=/api/test-service/**

